repos:
-   repo: local
    hooks:
    -   id: PreCommit
        name: Pre Commit
        entry: "make pre-commit-check"
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true