repos:
-   repo: local
    hooks:
    -   id: PreCommit
        name: Pre Commit
        entry: "./.pre-commit.sh on-commit"
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true