name: Feature request
description: Suggest a feature for the project
title: "[Feature]: "
labels: ["feature"]
assignees: ["leahevy"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe your feature
      description: A clear and concise description of your feature suggestion
      placeholder:
    validations:
      required: true
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. 
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder:
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here
      placeholder:
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/leahevy/template-python-project/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
