name: Release on GitHub

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Changelog
        run: .github/release_message.sh > release_message.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: release_message.md
